# Generated by Django 5.0.7 on 2024-08-12 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_tag_post_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
    ]
